# Generated by Django 6.0.6 on 2026-06-12 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('area_interes', models.CharField(choices=[('musica', 'Música'), ('deportes', 'Deportes')], max_length=10)),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(db_column='idCampus', on_delete=django.db.models.deletion.CASCADE, to='alumnos.campus')),
            ],
            options={
                'verbose_name_plural': 'Postulaciones',
            },
        ),
    ]
